--PRACTICAL-16

--PART-A

--Display players who belong to teams located in ‘Mumbai’. 
SELECT PLAYER.PLAYER_FIRST_NAME,TEAM.TEAM_NAME 
FROM TEAM INNER JOIN PLAYER
ON TEAM.TEAM_ID = PLAYER.TEAM_ID
WHERE TEAM.TEAM_NAME = 'Mumbai Indians'

--Display all teams and players. 
SELECT PLAYER.PLAYER_FIRST_NAME,TEAM.TEAM_NAME 
FROM TEAM INNER JOIN PLAYER
ON TEAM.TEAM_ID = PLAYER.TEAM_ID

--Display players along with team wins and stadium city. 
SELECT * FROM STADIUM,TEAM,PLAYER

SELECT PLAYER.PLAYER_FIRST_NAME, TEAM.TEAM_NAME, STADIUM.STADIUM_CITY
FROM PLAYER INNER JOIN TEAM INNER JOIN STADIUM
ON TEAM.HOME_STADIUM_ID = STADIUM.STADIUM_ID
ON TEAM.TEAM_ID = PLAYER.TEAM_ID

--Display team name and number of players in each team. 
SELECT TEAM.TEAM_NAME , COUNT(PLAYER.PLAYER_FIRST_NAME)
FROM PLAYER INNER JOIN TEAM
ON TEAM.TEAM_ID = PLAYER.TEAM_ID
GROUP BY TEAM.TEAM_NAME

--Display team name, coach, and number of bowlers in each team. 
SELECT TEAM.TEAM_NAME, TEAM.TEAM_COACH , COUNT(PLAYER.PLAYER_ROLE)
FROM TEAM INNER JOIN PLAYER
ON TEAM.TEAM_ID = PLAYER.TEAM_ID
WHERE PLAYER.PLAYER_ROLE = 'BOLWER'
GROUP BY TEAM.TEAM_NAME ,TEAM.TEAM_COACH
ORDER BY COUNT(PLAYER.PLAYER_ROLE)

--Display team name with count of batsmen, bowlers, and all-rounders. 
SELECT TEAM.TEAM_NAME, COUNT(PLAYER.PLAYER_ROLE)
FROM TEAM  JOIN PLAYER
ON TEAM.TEAM_ID = PLAYER.TEAM_ID
GROUP BY TEAM.TEAM_NAME , PLAYER.PLAYER_ROLE

--Display stadiums where teams have won more than 10 matches. 
SELECT STADIUM.Stadium_name
FROM STADIUM INNER JOIN TEAM
ON TEAM.HOME_STADIUM_ID = STADIUM.Stadium_id
WHERE TEAM.TEAM_TOTAL_MATCHES > 10

--Display team name and number of players whose matches played is greater than 25. 
SELECT TEAM.TEAM_NAME, COUNT(PLAYER.PLAYER_ID),SUM(PLAYER.PLAYER_MATCHES_PLAYED)
FROM TEAM INNER JOIN PLAYER
ON PLAYER.TEAM_ID = TEAM.TEAM_ID
GROUP BY TEAM.TEAM_NAME 
HAVING SUM(PLAYER.PLAYER_MATCHES_PLAYED) > 25

--Display team name and total number of players having jersey number greater than 30. 
SELECT TEAM.TEAM_NAME, COUNT(PLAYER.PLAYER_ID),COUNT(PLAYER.PLAYER_JERSEY_NUMBER)
FROM TEAM INNER JOIN PLAYER
ON TEAM.TEAM_ID = PLAYER.PLAYER_ID
GROUP BY TEAM.TEAM_NAME
HAVING count(PLAYER.PLAYER_JERSEY_NUMBER) > 30

--Display team name and total matches played by its players.
SELECT TEAM.TEAM_NAME, SUM(TEAM.TEAM_TOTAL_MATCHES)
FROM TEAM INNER JOIN PLAYER
ON PLAYER.TEAM_ID = TEAM.TEAM_ID
GROUP BY TEAM.TEAM_NAME

--PART-B

--Display stadium city and total number of teams in each city. 
SELECT STADIUM.Stadium_city ,SUM(TEAM.TEAM_ID)
FROM STADIUM INNER JOIN TEAM 
ON STADIUM.Stadium_id = TEAM.HOME_STADIUM_ID
GROUP BY STADIUM.Stadium_city

--Display team name and average matches played by players in each team. 
SELECT TEAM.TEAM_NAME, AVG(PLAYER.PLAYER_MATCHES_PLAYED)
FROM TEAM INNER JOIN PLAYER
ON TEAM.TEAM_ID = PLAYER.TEAM_ID
GROUP BY TEAM.TEAM_NAME

--Display team name and maximum matches played by any player in each team. 
SELECT TEAM.TEAM_NAME, MAX(PLAYER.PLAYER_MATCHES_PLAYED)
FROM TEAM INNER JOIN PLAYER
ON TEAM.TEAM_ID = PLAYER.TEAM_ID
GROUP BY TEAM.TEAM_NAME

--Display team name and minimum matches played by any player in each team. 
SELECT TEAM.TEAM_NAME, MIN(PLAYER.PLAYER_MATCHES_PLAYED)
FROM TEAM INNER JOIN PLAYER
ON TEAM.TEAM_ID = PLAYER.TEAM_ID
GROUP BY TEAM.TEAM_NAME

--Display stadium name and total number of players playing under teams of that stadium.
SELECT STADIUM.Stadium_name , TEAM.TEAM_NAME,COUNT(PLAYER.PLAYER_ID)
FROM STADIUM INNER JOIN TEAM INNER JOIN PLAYER
ON PLAYER.TEAM_ID = TEAM.TEAM_ID
ON STADIUM.Stadium_id = TEAM.HOME_STADIUM_ID
GROUP BY STADIUM.Stadium_name, TEAM.TEAM_NAME
