/* LAB 19 - SET OPERATORS*/


/* PART A */

/* 1. Unique customer names from ONLINE and OFFLINE */
SELECT Name FROM ONLINE_CUSTOMER
UNION
SELECT Name FROM OFFLINE_CUSTOMER;


/* 2. Unique customer cities */
SELECT CITY FROM ONLINE_CUSTOMER
UNION
SELECT CITY FROM OFFLINE_CUSTOMER;


/* 3. Duplicate customer names */
SELECT Name FROM ONLINE_CUSTOMER
INTERSECT
SELECT Name FROM OFFLINE_CUSTOMER;


/* 4. Unique customer IDs */
SELECT CID FROM ONLINE_CUSTOMER
UNION
SELECT CID FROM OFFLINE_CUSTOMER;


/* 5. GOLD customers and online customers */
SELECT Name
FROM CUSTOMER
WHERE MEMBERSHIP = 'GOLD'
UNION
SELECT Name
FROM ONLINE_CUSTOMER;


/* 6. Names from CUSTOMER and ONLINE_CUSTOMER */
SELECT Name FROM CUSTOMER
UNION
SELECT Name FROM ONLINE_CUSTOMER;


/* 7. Cities from CUSTOMER and OFFLINE_CUSTOMER */
SELECT CITY FROM CUSTOMER
UNION
SELECT CITY FROM OFFLINE_CUSTOMER;


/* 8. Customer IDs using UNION ALL */
SELECT CID FROM CUSTOMER
UNION ALL
SELECT CID FROM OFFLINE_CUSTOMER;


/* 9. Customer names from RAJKOT */
SELECT Name
FROM CUSTOMER
WHERE CITY = 'RAJKOT'
UNION
SELECT Name
FROM ONLINE_CUSTOMER
WHERE CITY = 'RAJKOT';


/* 10. Names starting with R */
SELECT Name
FROM CUSTOMER
WHERE Name LIKE 'R%'
UNION
SELECT Name
FROM ONLINE_CUSTOMER
WHERE Name LIKE 'R%';


/* 11. Customers who are both ONLINE and OFFLINE */
SELECT Name FROM ONLINE_CUSTOMER
INTERSECT
SELECT Name FROM OFFLINE_CUSTOMER;


/* 12. IDs existing in both */
SELECT CID FROM ONLINE_CUSTOMER
INTERSECT
SELECT CID FROM OFFLINE_CUSTOMER;


/* 13. Names only in ONLINE */
SELECT Name FROM ONLINE_CUSTOMER
EXCEPT
SELECT Name FROM OFFLINE_CUSTOMER;


/* 14. Names only in OFFLINE */
SELECT Name FROM OFFLINE_CUSTOMER
EXCEPT
SELECT Name FROM ONLINE_CUSTOMER;


/* 15. Cities available in both */
SELECT CITY FROM ONLINE_CUSTOMER
INTERSECT
SELECT CITY FROM OFFLINE_CUSTOMER;


/* PART B */

/* 16. GOLD members who are online */
SELECT Name
FROM CUSTOMER
WHERE MEMBERSHIP = 'GOLD'
INTERSECT
SELECT Name
FROM ONLINE_CUSTOMER;


/* 17. PLATINUM members but not online */
SELECT Name
FROM CUSTOMER
WHERE MEMBERSHIP = 'PLATINUM'
EXCEPT
SELECT Name
FROM ONLINE_CUSTOMER;


/* 18. Online but not offline */
SELECT CID
FROM ONLINE_CUSTOMER
EXCEPT
SELECT CID
FROM OFFLINE_CUSTOMER;


/* 19. Offline but not online */
SELECT CID
FROM OFFLINE_CUSTOMER
EXCEPT
SELECT CID
FROM ONLINE_CUSTOMER;


/* 20. In CUSTOMER but not ONLINE */
SELECT Name
FROM CUSTOMER
EXCEPT
SELECT Name
FROM ONLINE_CUSTOMER;


/* 21. GOLD members and OFFLINE */
SELECT Name
FROM CUSTOMER
WHERE MEMBERSHIP = 'GOLD'
INTERSECT
SELECT Name
FROM OFFLINE_CUSTOMER;


/* 22. Distinct cities from all three tables */
SELECT CITY FROM CUSTOMER
UNION
SELECT CITY FROM ONLINE_CUSTOMER
UNION
SELECT CITY FROM OFFLINE_CUSTOMER;


/* 23. Online customers from SURAT */
SELECT Name
FROM ONLINE_CUSTOMER
WHERE CITY = 'SURAT'
INTERSECT
SELECT Name
FROM ONLINE_CUSTOMER;


/* 24. Offline customers but not RAJKOT
   SQL Server uses EXCEPT instead of MINUS */
SELECT Name
FROM OFFLINE_CUSTOMER
EXCEPT
SELECT Name
FROM OFFLINE_CUSTOMER
WHERE CITY = 'RAJKOT';


/* 25. GOLD + ONLINE + SURAT */
SELECT Name
FROM CUSTOMER
WHERE MEMBERSHIP = 'GOLD'
AND CITY = 'SURAT'
INTERSECT
SELECT Name
FROM ONLINE_CUSTOMER
WHERE CITY = 'SURAT';


/* PART C */

/* 26. Names present in at least two tables */
SELECT Name
FROM CUSTOMER
INTERSECT
SELECT Name
FROM ONLINE_CUSTOMER

UNION

SELECT Name
FROM CUSTOMER
INTERSECT
SELECT Name
FROM OFFLINE_CUSTOMER

UNION

SELECT Name
FROM ONLINE_CUSTOMER
INTERSECT
SELECT Name
FROM OFFLINE_CUSTOMER;


/* 27. CUSTOMER names excluding names
   present in both ONLINE and OFFLINE */
SELECT Name
FROM CUSTOMER
EXCEPT
(
    SELECT Name
    FROM ONLINE_CUSTOMER
    INTERSECT
    SELECT Name
    FROM OFFLINE_CUSTOMER
);


/* 28. ONLINE + OFFLINE but not PLATINUM */
SELECT Name
FROM ONLINE_CUSTOMER
INTERSECT
SELECT Name
FROM OFFLINE_CUSTOMER
EXCEPT
SELECT Name
FROM CUSTOMER
WHERE MEMBERSHIP = 'PLATINIUM';


/* 29. Either ONLINE or OFFLINE but not both */
(
    SELECT Name FROM ONLINE_CUSTOMER
    EXCEPT
    SELECT Name FROM OFFLINE_CUSTOMER
)
UNION
(
    SELECT Name FROM OFFLINE_CUSTOMER
    EXCEPT
    SELECT Name FROM ONLINE_CUSTOMER
);


/* 30. CUSTOMER IDs missing from both ONLINE and OFFLINE */
SELECT CID
FROM CUSTOMER
EXCEPT
SELECT CID
FROM ONLINE_CUSTOMER

EXCEPT
SELECT CID
FROM OFFLINE_CUSTOMER;
