--PRACTICAL-13

--PART-A

--Combine information from Student and Result table using cross join (Cartesian product). 
SELECT * FROM STUDENT,RESULT

--Perform inner join on Student and Result tables. 
SELECT * FROM 
STUDENT INNER JOIN RESULT 
ON STUDENT.STDID = RESULT.RNO

--Perform the left outer join on Student and Result tables. 
SELECT * FROM
STUDENT LEFT OUTER JOIN RESULT
ON STUDENT.STDID = RESULT.RNO

--Perform the right outer join on Student and Result tables. 
SELECT * FROM
STUDENT RIGHT OUTER JOIN RESULT
ON STUDENT.STDID = RESULT.RNO

--Perform the full outer join on Student and Result tables. 
SELECT * FROM
STUDENT FULL OUTER JOIN RESULT
ON STUDENT.STDID = RESULT.RNO

--Display Rno, Name, Branch and SPI of all students. 
SELECT RNO,SNAME,BRANCH FROM 
STUDENT FULL OUTER JOIN RESULT 
ON  STUDENT.STDID = RESULT.RNO

--Display Rno, Name, Branch and SPI of CE branch students only. 
SELECT RESULT.RNO,STUDENT.SNAME,STUDENT.BRANCH FROM
STUDENT JOIN RESULT 
ON  STUDENT.STDID = RESULT.RNO
WHERE BRANCH='COMPUTER'

--Display Rno, Name, Branch and SPI of students other than EC branch. 
SELECT RESULT.RNO,STUDENT.SNAME,STUDENT.BRANCH,RESULT.SPI FROM
STUDENT JOIN RESULT 
ON  STUDENT.STDID = RESULT.RNO
WHERE NOT BRANCH='ELECTRICAL'

--Display Rno, Name and SPI of students whose SPI is greater than 8. 
SELECT RESULT.RNO,STUDENT.SNAME,STUDENT.BRANCH,RESULT.SPI FROM
STUDENT JOIN RESULT 
ON  STUDENT.STDID = RESULT.RNO
WHERE RESULT.SPI > 8

--Display Rno, Name and Branch of students whose SPI is less than 8. 
SELECT RESULT.RNO,STUDENT.SNAME,STUDENT.BRANCH FROM
STUDENT JOIN RESULT 
ON  STUDENT.STDID = RESULT.RNO
WHERE RESULT.SPI < 8

--Display average result of each branch. 
SELECT STUDENT.BRANCH ,AVG(RESULT.SPI) FROM
STUDENT JOIN RESULT 
ON  STUDENT.STDID = RESULT.RNO
GROUP BY STUDENT.BRANCH

--Display average result of CE and ME branch. 
SELECT STUDENT.BRANCH ,AVG(RESULT.SPI) FROM
STUDENT JOIN RESULT 
ON  STUDENT.STDID = RESULT.RNO
WHERE BRANCH='COMPUTER' OR BRANCH='MECHANICAL'
GROUP BY STUDENT.BRANCH

--Display maximum and minimum SPI of each branch. 
SELECT STUDENT.BRANCH ,MIN(RESULT.SPI) AS MINSPI , MAX(RESULT.SPI) AS MAXSPI FROM
STUDENT JOIN RESULT 
ON  STUDENT.STDID = RESULT.RNO
GROUP BY STUDENT.BRANCH

--Display branch-wise student count in descending order. 
SELECT STUDENT.BRANCH ,COUNT(RESULT.SPI) AS COUNT FROM
STUDENT JOIN RESULT 
ON  STUDENT.STDID = RESULT.RNO
GROUP BY STUDENT.BRANCH
ORDER BY COUNT(RESULT.SPI) DESC 

--Display branch-wise total SPI of students.
SELECT STUDENT.BRANCH ,SUM(RESULT.SPI) AS TOTAL FROM
STUDENT JOIN RESULT 
ON  STUDENT.STDID = RESULT.RNO
GROUP BY STUDENT.BRANCH 

--PART-B

--Display branch-wise number of students having SPI greater than 8. 
SELECT STUDENT.BRANCH ,COUNT(RESULT.SPI) AS NUMSTUDENTS FROM
STUDENT JOIN RESULT 
ON  STUDENT.STDID = RESULT.RNO
WHERE RESULT.SPI > 8
GROUP BY STUDENT.BRANCH

--Display branch-wise number of students having SPI less than 8. 
SELECT STUDENT.BRANCH ,COUNT(RESULT.SPI) AS NUMSTUDENTS FROM
STUDENT JOIN RESULT 
ON  STUDENT.STDID = RESULT.RNO
WHERE RESULT.SPI < 8
GROUP BY STUDENT.BRANCH

-- Display branch-wise average SPI greater than 7. 
SELECT STUDENT.BRANCH ,AVG(RESULT.SPI) AS AVGSPI FROM
STUDENT JOIN RESULT 
ON  STUDENT.STDID = RESULT.RNO
WHERE RESULT.SPI > 7
GROUP BY STUDENT.BRANCH 

--Display branches having more than 1 students. 
SELECT STUDENT.BRANCH ,COUNT(STUDENT.BRANCH) FROM
STUDENT JOIN RESULT  
ON  STUDENT.STDID = RESULT.RNO
GROUP BY STUDENT.BRANCH 
HAVING COUNT(STUDENT.BRANCH) > 1

--Display branches where maximum SPI is greater than 9. 
SELECT STUDENT.BRANCH ,MAX(RESULT.SPI) AS MAXSPI FROM
STUDENT JOIN RESULT 
ON  STUDENT.STDID = RESULT.RNO
GROUP BY STUDENT.BRANCH 
HAVING MAX(RESULT.SPI) > 9

--PART-C

--Display average result of each branch and sort them in ascending order by SPI. 
SELECT STUDENT.BRANCH ,AVG(RESULT.SPI) FROM
STUDENT JOIN RESULT 
ON  STUDENT.STDID = RESULT.RNO
GROUP BY STUDENT.BRANCH
ORDER BY AVG(RESULT.SPI)

--Display highest SPI from each branch and sort them in descending order. 
SELECT STUDENT.BRANCH ,MAX(RESULT.SPI) FROM
STUDENT JOIN RESULT 
ON  STUDENT.STDID = RESULT.RNO
GROUP BY STUDENT.BRANCH
ORDER BY MAX(RESULT.SPI) DESC

--Display average result of each branch and sort them in ascending order by SPI. 
SELECT STUDENT.BRANCH ,AVG(RESULT.SPI) FROM
STUDENT JOIN RESULT 
ON  STUDENT.STDID = RESULT.RNO
GROUP BY STUDENT.BRANCH
ORDER BY AVG(RESULT.SPI) 

--Display highest SPI from each branch and sort them in descending order. 
SELECT STUDENT.BRANCH ,MAX(RESULT.SPI) FROM
STUDENT JOIN RESULT 
ON  STUDENT.STDID = RESULT.RNO
GROUP BY STUDENT.BRANCH
ORDER BY MAX(RESULT.SPI) DESC

--Display branches where difference between max and min SPI is greater than 1.
SELECT STUDENT.BRANCH ,MAX(RESULT.SPI)-MIN(RESULT.SPI) FROM
STUDENT JOIN RESULT 
ON  STUDENT.STDID = RESULT.RNO
GROUP BY STUDENT.BRANCH
HAVING MAX(RESULT.SPI)-MIN(RESULT.SPI) > 1
