--PRACTICAL-14

--PART-A

--Combine information from Person and Department table using cross join or Cartesian product. 
SELECT * FROM PERSON, DEPARTMENT 

--Find all persons with their department name 
SELECT PERSON.PERSONNAME ,DEPARTMENT.DEPARTMENTNAME  FROM
PERSON JOIN DEPARTMENT
ON  PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID 

--Find all persons with their department name & code.
SELECT PERSON.PERSONNAME ,DEPARTMENT.DEPARTMENTNAME,DEPARTMENT.DEPARTMENTCODE  FROM
PERSON JOIN DEPARTMENT
ON  PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID 

--Find all persons with their department code and location. 
SELECT PERSON.PERSONNAME ,DEPARTMENT.DEPARTMENTCODE ,DEPARTMENT.LOCATION FROM
PERSON JOIN DEPARTMENT
ON  PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID 

--Find the detail of the person who belongs to Mechanical department.
SELECT *  FROM
PERSON LEFT JOIN DEPARTMENT
ON  PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID  
WHERE DEPARTMENT.DEPARTMENTNAME='MECHANICAL'

--Final person’s name, department code and salary who lives in Ahmedabad city.  
SELECT PERSON.PERSONNAME ,DEPARTMENT.DEPARTMENTCODE ,PERSON.SALARY FROM
PERSON JOIN DEPARTMENT
ON  PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
WHERE PERSON.CITY = 'AHMEDABAD' 

--Find the person's name whose department is in C-Block. 
SELECT PERSON.PERSONNAME FROM
PERSON JOIN DEPARTMENT
ON  PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
WHERE DEPARTMENT.LOCATION = 'C-BLOCK' 

--Retrieve person name, salary & department name who belongs to Jamnagar city. 
SELECT PERSON.PERSONNAME ,DEPARTMENT.DEPARTMENTNAME ,PERSON.SALARY FROM
PERSON JOIN DEPARTMENT
ON  PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
WHERE PERSON.CITY = 'JAMNAGAR' 

--Retrieve person’s detail who joined the Civil department after 1-Aug-2001. 
SELECT * FROM
PERSON JOIN DEPARTMENT
ON  PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
WHERE DEPARTMENT.DEPARTMENTNAME='CIVIL' AND PERSON.JOININGDATE > '1-Aug-2001'

--Display all the person's name with the department whose joining date difference with the current date is more than 25 years. 
SELECT PERSON.PERSONNAME ,DEPARTMENT.DEPARTMENTNAME FROM
PERSON JOIN DEPARTMENT
ON  PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
WHERE DATEDIFF(YEAR,PERSON.JOININGDATE,GETDATE()) > 25

--Find department wise person counts. 
SELECT DEPARTMENT.DEPARTMENTNAME, COUNT(PERSON.PERSONNAME) FROM
PERSON JOIN DEPARTMENT
ON  PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
GROUP BY DEPARTMENT.DEPARTMENTNAME

--Give department wise maximum & minimum salary with department name. 
SELECT DEPARTMENT.DEPARTMENTNAME, MAX(PERSON.SALARY) AS MAXSALARY ,MIN(PERSON.SALARY) AS MINSALARY FROM
PERSON JOIN DEPARTMENT
ON  PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
GROUP BY DEPARTMENT.DEPARTMENTNAME

--Find city wise total, average, maximum and minimum salary. 
SELECT PERSON.CITY, MAX(PERSON.SALARY) AS MAXSALARY ,MIN(PERSON.SALARY) AS MINSALARY ,SUM(PERSON.SALARY) AS MAXSALARY,AVG(PERSON.SALARY) AS MAXSALARY  FROM
PERSON JOIN DEPARTMENT
ON  PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
GROUP BY PERSON.CITY 

--Find the average salary of a person who belongs to Ahmedabad city. 
SELECT PERSON.CITY,AVG(PERSON.SALARY) AS AVGSALARY FROM
PERSON JOIN DEPARTMENT
ON  PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
WHERE PERSON.CITY='AHMEDABAD'
GROUP BY PERSON.CITY

--Produce Output Like: <PersonName> lives in <City> and works in <DepartmentName> Department. (In single column) 
SELECT PERSON.PERSONNAME+' LIVES IN '+PERSON.CITY+' AND WORKS IN '+DEPARTMENT.DEPARTMENTNAME+' DEPARTMENT' AS PERSONDATA FROM
PERSON JOIN DEPARTMENT
ON  PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID

--PART-B

--Produce Output Like: <PersonName> earns <Salary> from <DepartmentName> department monthly. (In single column) 
SELECT PERSON.PERSONNAME+' EARNS '+CAST(PERSON.SALARY AS VARCHAR)+' FROM '+DEPARTMENT.DEPARTMENTNAME+' DEPARTMENT MONTHLY' AS PERSONDATA FROM
PERSON JOIN DEPARTMENT
ON  PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID

--Find city & department wise total, average & maximum salaries. 
SELECT PERSON.CITY,DEPARTMENT.DEPARTMENTNAME, MAX(PERSON.SALARY) AS MAXSALARY ,SUM(PERSON.SALARY) AS TOTALSALARY,AVG(PERSON.SALARY) AS AVGSALARY  FROM
PERSON JOIN DEPARTMENT
ON  PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
GROUP BY PERSON.CITY ,DEPARTMENT.DEPARTMENTNAME

--Find all persons who do not belong to any department. 
SELECT DEPARTMENT.DEPARTMENTNAME, COUNT(DEPARTMENT.DEPARTMENTNAME)  FROM
PERSON JOIN DEPARTMENT
ON  PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
WHERE DEPARTMENT.DEPARTMENTNAME IS NULL
GROUP BY DEPARTMENT.DEPARTMENTNAME

--Find all departments whose total salary is exceeding 100000. 
select DEPARTMENT.DEPARTMENTNAME,sum(person.SALARY)
FROM PERSON JOIN DEPARTMENT
ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
GROUP BY DEPARTMENT.DEPARTMENTNAME
HAVING SUM(PERSON.SALARY)>100000

--PART-C

--List all departments who have no person.
select DEPARTMENT.DEPARTMENTNAME,COUNT(person.PERSONID)
FROM PERSON JOIN DEPARTMENT
ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
GROUP BY DEPARTMENT.DEPARTMENTNAME
HAVING COUNT(PERSON.PERSONID) = 0

--List out department names in which more than two persons are working. 
select DEPARTMENT.DEPARTMENTNAME,COUNT(person.PERSONID)
FROM PERSON JOIN DEPARTMENT
ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
GROUP BY DEPARTMENT.DEPARTMENTNAME
HAVING COUNT(PERSON.PERSONID) > 2

--give a 10% increment in the computer department employee’s salary. (Use Update) 
UPDATE PERSON  SET SALARY= SALARY+(30*100) 
FROM PERSON JOIN DEPARTMENT
ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
WHERE DEPARTMENT.DEPARTMENTNAME = 'COMPUTER'
