--PRACTICAL-15

--PART-A

--List all books with their authors. 
SELECT BOOK.TITLE,AUTHOR.AUTHORNAME
FROM BOOK INNER JOIN AUTHOR
ON BOOK.AUTHORID = AUTHOR.AUTHORID

--List all books with their publishers.
SELECT BOOK.TITLE,PUBLISHER.PUBLISHERNAME
FROM BOOK INNER JOIN PUBLISHER
ON BOOK.PUBLISHERID = PUBLISHER.PUBLISHERID

--List all books with their authors and publishers. 
SELECT BOOK.TITLE,AUTHOR.AUTHORNAME,PUBLISHER.PUBLISHERNAME
FROM PUBLISHER INNER JOIN AUTHOR INNER JOIN BOOK
ON BOOK.AUTHORID = AUTHOR.AUTHORID
ON BOOK.PUBLISHERID = PUBLISHER.PUBLISHERID

--List all books published after 2010 with their authors and publisher and price. 
SELECT BOOK.TITLE,AUTHOR.AUTHORNAME,PUBLISHER.PUBLISHERNAME,BOOK.PRICE
FROM PUBLISHER INNER JOIN AUTHOR INNER JOIN BOOK
ON BOOK.AUTHORID = AUTHOR.AUTHORID
ON BOOK.PUBLISHERID = PUBLISHER.PUBLISHERID
WHERE BOOK.PUBLICATIONYEAR > 2010

--List all authors and the number of books they have written. 
SELECT AUTHOR.AUTHORNAME,COUNT(BOOK.BOOKID) AS NUMBER_OF_BOOKS
FROM AUTHOR INNER JOIN BOOK
ON BOOK.AUTHORID = AUTHOR.AUTHORID
GROUP BY AUTHOR.AUTHORNAME

--List all publishers and the total price of books they have published.
SELECT PUBLISHER.PUBLISHERNAME,SUM(BOOK.PRICE)
FROM PUBLISHER INNER JOIN BOOK
ON BOOK.PUBLISHERID = PUBLISHER.PUBLISHERID
GROUP BY PUBLISHER.PUBLISHERNAME

--List authors who have not written any books. 
SELECT AUTHOR.AUTHORNAME,COUNT(BOOK.BOOKID) AS NUMBER_OF_BOOKS
FROM AUTHOR INNER JOIN BOOK
ON BOOK.AUTHORID = AUTHOR.AUTHORID
GROUP BY AUTHOR.AUTHORNAME
HAVING COUNT(BOOK.BOOKID) = 0

--Display the total number of books written by each author along with the average price of their books. 
SELECT AUTHOR.AUTHORNAME,COUNT(BOOK.BOOKID)  AS NUMBER_OF_BOOKS,AVG(BOOK.PRICE) AS AVG_PRICE
FROM AUTHOR INNER JOIN BOOK
ON BOOK.AUTHORID = AUTHOR.AUTHORID
GROUP BY AUTHOR.AUTHORNAME

--lists each publisher along with the total number of books they have published, sorted from highest to lowest. 
SELECT PUBLISHER.PUBLISHERNAME,COUNT(BOOK.BOOKID)
FROM PUBLISHER INNER JOIN BOOK
ON BOOK.PUBLISHERID = PUBLISHER.PUBLISHERID
GROUP BY PUBLISHER.PUBLISHERNAME
ORDER BY COUNT(BOOK.BOOKID) DESC

--Display number of books published each year.
SELECT BOOK.PUBLICATIONYEAR,COUNT(BOOK.BOOKID)
FROM PUBLISHER INNER JOIN BOOK
ON BOOK.PUBLISHERID = PUBLISHER.PUBLISHERID
GROUP BY BOOK.PUBLICATIONYEAR

--PART-B

CREATE TABLE EMPLOYEE_MASTER(
	EmployeeNo INT,
	Name VARCHAR(50),
	ManagerNo INT
)

INSERT INTO EMPLOYEE_MASTER VALUES
('E01','Tarun',NULL),
('E02','Rohan','E02'),
('E03','Priya','E01'),
('E04','Milan','E03'),
('E05','Jay','E01'),
('E06','Anjana','E04')

--List the publishers whose total book prices exceed 500, ordered by the total price. 
SELECT PUBLISHER.PUBLISHERNAME,SUM(BOOK.PRICE)
FROM PUBLISHER INNER JOIN BOOK
ON BOOK.PUBLISHERID = PUBLISHER.PUBLISHERID
GROUP BY PUBLISHER.PUBLISHERNAME
HAVING SUM(BOOK.PRICE) > 500
ORDER BY SUM(BOOK.PRICE)

--List most expensive book for each author, sort it with the highest price. 
SELECT AUTHOR.AUTHORNAME,MAX(BOOK.PRICE)
FROM BOOK INNER JOIN AUTHOR 
ON BOOK.AUTHORID = AUTHOR.AUTHORID
GROUP BY AUTHOR.AUTHORNAME
ORDER BY MAX(BOOK.PRICE) DESC

--Display publisher name and difference between maximum and minimum book price. 
SELECT PUBLISHER.PUBLISHERNAME , MAX(BOOK.PRICE)-MIN(BOOK.PRICE)
FROM PUBLISHER INNER JOIN BOOK
ON BOOK.PUBLISHERID = PUBLISHER.PUBLISHERID
GROUP BY PUBLISHER.PUBLISHERNAME

--List publisher name and total price of books published each year.
SELECT PUBLISHER.PUBLISHERNAME , BOOK.PUBLICATIONYEAR ,SUM(BOOK.PRICE)
FROM PUBLISHER INNER JOIN BOOK
ON BOOK.PUBLISHERID = PUBLISHER.PUBLISHERID
GROUP BY PUBLISHER.PUBLISHERNAME, BOOK.PUBLICATIONYEAR

--Display author name and total price of books sorted by highest total price.
SELECT AUTHOR.AUTHORNAME , SUM(BOOK.PRICE)
FROM AUTHOR INNER JOIN BOOK
ON BOOK.AUTHORID = AUTHOR.AUTHORID
GROUP BY AUTHOR.AUTHORNAME
ORDER BY SUM(BOOK.PRICE) DESC 

--PART-C

--Retrieve the names of employee along with their manager’s name from the Employee table. 
SELECT E.NAME AS EMPLOYEE , M.NAME AS MANAGER
FROM EMPLOYEE_MASTER E INNER JOIN EMPLOYEE_MASTER M
ON M.ManagerNo = E.EmployeeNo

--Display employees who are managers. 
SELECT E.NAME AS EMPLOYEE , M.NAME AS MANAGER
FROM EMPLOYEE_MASTER E INNER JOIN EMPLOYEE_MASTER M
ON M.ManagerNo = E.EmployeeNo
WHERE E.NAME = M.NAME

--Display number of employees working under each manager. 
SELECT M.NAME AS MANAGER, COUNT(E.NAME) AS TOTAL_EMPLOYEE
FROM EMPLOYEE_MASTER E INNER JOIN EMPLOYEE_MASTER M
ON M.ManagerNo = E.EmployeeNo
GROUP BY M.NAME

--Display the employee’s name along with their manager’s name and senior manager name. 
SELECT E.NAME AS EMPLOYEE , M.NAME AS MANAGER, S.NAME AS SENIORMANAGER
FROM EMPLOYEE_MASTER E INNER JOIN EMPLOYEE_MASTER M INNER JOIN EMPLOYEE_MASTER S
ON M.ManagerNo = S.ManagerNo
ON M.ManagerNo = E.EmployeeNo

--Display managers and count of employees under them in descending order. 
SELECT M.NAME AS MANAGER,COUNT(E.NAME)
FROM EMPLOYEE_MASTER E INNER JOIN EMPLOYEE_MASTER M 
ON M.ManagerNo = E.EmployeeNo
GROUP BY M.Name
ORDER BY COUNT(E.Name) DESC
