--PRACTICAL-20

--Display rank of students based on SPI. 
SELECT STDID,SNAME,SPI,
RANK() OVER (ORDER BY SPI) AS [RANK]
FROM STUDENT

--Display dense rank of students based on SPI. 
SELECT STDID,SNAME,SPI,
DENSE_RANK() OVER (ORDER BY SPI) AS [RANK]
FROM STUDENT

--Display sequential number for each student record. 
SELECT STDID,SNAME,SPI,
ROW_NUMBER() OVER (ORDER BY SPI) AS [RANK]
FROM STUDENT

--Display branch-wise rank of students. 
SELECT STDID,SNAME,BRANCH,
RANK() OVER (ORDER BY BRANCH) AS [B_RANK]
FROM STUDENT

--Display branch-wise dense ranking of students. 
SELECT STDID,SNAME,BRANCH,
DENSE_RANK() OVER (ORDER BY BRANCH) AS [B_RANK]
FROM STUDENT

--Display branch-wise sequential numbering of students. 
SELECT STDID,SNAME,BRANCH,
ROW_NUMBER() OVER (ORDER BY BRANCH) AS [B_RANK]
FROM STUDENT

--Display SNAME, Current SPI, Previous SPI and SPI Difference with previous student in ascending order of SPI. 
SELECT STDID,SNAME,SPI AS Current_SPI,
LAG(SPI) OVER (ORDER BY SPI) AS Previous_SPI,
SPI-LAG(SPI) OVER (ORDER BY SPI) AS Difference
FROM STUDENT

--Display SNAME, Current SPI, Next SPI and SPI Difference with next student in descending order of SPI. 
SELECT STDID,SNAME,SPI AS Current_SPI,
LEAD(SPI) OVER (ORDER BY SPI) AS Next_SPI,
SPI-LEAD(SPI) OVER (ORDER BY SPI DESC) AS Difference
FROM STUDENT

--Display top 3 students based on SPI.
SELECT TOP 3 STDID,SNAME,SPI,
RANK() OVER (ORDER BY SPI) AS [RANK]
FROM STUDENT 

--Display top 2 students from each branch.
SELECT TOP 2 STDID,SNAME,BRANCH,
RANK() OVER (ORDER BY BRANCH) AS [B_RANK]
FROM STUDENT 

--PART-B

-- Display 5th highest SPI.
WITH STUDENTRANK AS
(SELECT STDID,SNAME,SPI,
DENSE_RANK() OVER (ORDER BY SPI DESC) AS RANKNO
FROM STUDENT)
SELECT * FROM STUDENTRANK 

-- Display 6th highest SPI. 
WITH STUDENTRANK AS
(SELECT STDID,SNAME,SPI,
DENSE_RANK() OVER (ORDER BY SPI DESC) AS RANKNO
FROM STUDENT)
SELECT * FROM STUDENTRANK WHERE RANKNO = 6

--Display students having same ranking. 
WITH STUDENTRANK AS
(SELECT STDID,SNAME,SPI,
DENSE_RANK() OVER (ORDER BY SPI DESC) AS RANKNO
FROM STUDENT)
SELECT * FROM STUDENTRANK 

--Display SNAME, Previous SPI, Current SPI and Next SPI based on ascending order of SPI. 
WITH STUDENTRANK AS
(SELECT STDID,SNAME,SPI,
LAG(SPI) OVER (ORDER BY SPI) AS Previous_SPI,
LEAD(SPI) OVER (ORDER BY SPI) AS Current_SPI
FROM STUDENT)
SELECT * FROM STUDENTRANK

--Display topper of each branch. 
WITH STUDENTRANK AS
(SELECT STDID,SNAME,BRANCH,
DENSE_RANK() OVER (PARTITION BY BRANCH ORDER BY BRANCH) AS [B_RANK]
FROM STUDENT)
SELECT * FROM STUDENTRANK WHERE B_RANK = 1
